before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: colr-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/colr.version={{.Version}} -X github.com/k1LoW/colr.commit={{.FullCommit}} -X github.com/k1LoW/colr.date={{.Date}} -X github.com/k1LoW/colr/version.Version={{.Version}}
-
  id: colr-darwin-windows
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/colr.version={{.Version}} -X github.com/k1LoW/colr.commit={{.FullCommit}} -X github.com/k1LoW/colr.date={{.Date}} -X github.com/k1LoW/colr/version.Version={{.Version}}
archives:
-
  id: colr-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
  -
    name: colr
    ids:
      - colr-archive
    tap:
      owner: k1LoW
      name: homebrew-tap
    commit_author:
      name: k1LoW
      email: k1lowxb@gmail.com
    homepage: https://github.com/k1LoW/colr
    description: colr colors strings, colorfully.
    license: MIT
    install: |
      bin.install 'colr'
nfpms:
  -
    id: colr-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - colr-linux
    homepage: https://github.com/k1LoW/colr
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: colr colors strings, colorfully.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
