name: build

on: push

jobs:
  job-test:
    name: Test
    strategy:
      matrix:
        go_version: [1.12, 1.13]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install codecov
        if: matrix.platform == 'ubuntu-latest'
        run: sudo pip install codecov

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: env PATH=`go env GOPATH`/bin:$PATH make ci
        if: matrix.platform != 'windows-latest'
        env:
          GOPROXY: "https://proxy.golang.org"

      - name: Test
        run: |
          go test ./...
          go test ./... -tags integration
        shell: cmd
        if: matrix.platform == 'windows-latest'
        env:
          GO111MODULE: on
          GOPROXY: "https://proxy.golang.org"

      - name: Run codecov
        if: matrix.platform == 'ubuntu-latest'
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
