name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    strategy:
      matrix:
        go_version: [1.17]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Test
        run: make ci
        if: matrix.platform != 'windows-latest'

      - name: Test
        run: |
          go test ./...
          go test ./... -tags integration
        shell: cmd
        if: matrix.platform == 'windows-latest'

      - name: Run octocov
        if: matrix.platform == 'ubuntu-latest'
        uses: k1LoW/octocov-action@v0
