name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Run lint
        if: matrix.platform == 'ubuntu-latest'
        uses: reviewdog/action-golangci-lint@v2

      - name: Test
        if: matrix.platform != 'windows-latest'
        run: make ci

      - name: Test
        if: matrix.platform == 'windows-latest'
        run: |
          go test ./...
          go test ./... -tags integration
        shell: cmd

      - name: Run octocov
        if: matrix.platform == 'ubuntu-latest'
        uses: k1LoW/octocov-action@v0
